# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad2c187f3f3df2d27f69efeb0fbcd805a6a27e0e0e562ec179d7e88ca29b6a800143cc03c220f3dd26b1831a20e8553334e9b8d9b9273c40f1ec0fcf5230145

test:
  secret_key_base: 0303a010210a7c99b28cde0c74b1d20969589f8a0093c60a950a2805eeecfe779b35764b68e20090d053b13e18cb8b8f0444348f589ad82e90fd9f92567966d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
